[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.6.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
